on:
  push:
    branches:
      - "gh-pages"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Deploy Storybook
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: storybook-static
          install_command: pnpm install --no-frozen-lockfile
          build_command: pnpm run build-storybook
          checkout: false